export const FLIP_CARD = "FLIP_CARD";
export type FLIP_CARD = typeof FLIP_CARD;

export const RESTART_GAME = "RESTART_GAME";
export type RESTART_GAME = typeof RESTART_GAME;

export const INCREMENT_POINTS = "INCREMENT_POINTS";
export type INCREMENT_POINTS = typeof INCREMENT_POINTS;

export const INCREMENT_MULTIPLYER = "INCREMENT_MULTIPLYER";
export type INCREMENT_MULTIPLYER = typeof INCREMENT_MULTIPLYER;

export const RESET_MULTIPLYER = "RESET_MULTIPLYER";
export type RESET_MULTIPLYER = typeof RESET_MULTIPLYER;